### ISSUE TITLE
出现误报很多，能修复这些问题吗？

### ISSUE THREAD

**Issue by sankexin** [samylee/Amazing_Head_Detection#1]
随便测了一下视频，误报很多，比如：手、脚、椅子、电脑、午睡床等等，能解决这些问题吗？只报人才正常啊，下面是一些截图的误报情况：

![3](https://user-images.githubusercontent.com/33318353/72588447-57f4d580-3933-11ea-86f8-a29e92841b4d.png)
![1](https://user-images.githubusercontent.com/33318353/72588450-59260280-3933-11ea-8933-04f936fd56c9.png)
![2](https://user-images.githubusercontent.com/33318353/72588455-5b885c80-3933-11ea-8e75-b36fe7250326.png)
![4](https://user-images.githubusercontent.com/33318353/72588456-5c20f300-3933-11ea-9158-44d37dbcc210.png)
![5](https://user-images.githubusercontent.com/33318353/72588457-5cb98980-3933-11ea-8502-89cd039b46c0.png)
![6](https://user-images.githubusercontent.com/33318353/72588460-5deab680-3933-11ea-8917-ed1eed129080.png)
![7](https://user-images.githubusercontent.com/33318353/72588462-5e834d00-3933-11ea-8d74-dbc3086c8f0d.png)
![8](https://user-images.githubusercontent.com/33318353/72588464-5f1be380-3933-11ea-91fe-7a868a6de575.png)
![9](https://user-images.githubusercontent.com/33318353/72588465-5fb47a00-3933-11ea-9923-55f4c044a307.png)

**Comment by samylee** [comment]
@sankexin 你好，很抱歉回复晚了，误报可以解决，只需要加入测试场景训练集微调即可，手和腿均属于人体，所以被检测到了！

**Comment by samylee** [comment]
@sankexin 额  这个是检测人头的github，我转去人体回答了！

**Comment by samylee** [comment]
solved!
